In [1]:
import numpy as np

# Array Creation

In [5]:
# creating one-dimensional array from a python list
_list = [1,2,3,4]

arr = np.array(_list)
arr

array([1, 2, 3, 4])

In [7]:
print(arr.size)   # len of the numpy array
print(arr.ndim)   # number of dimensions
print(arr.dtype)  # data type of the array

4
1
int64


In [8]:
np.zeros((2, 3))  # 2x3 array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3, 3))   # 3x3 array of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.eye(4)         # 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
# create numpy array using range
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [17]:
arr = np.random.randint(1, 10, (2, 3))   # Random ints from 1 to 9 in 2x3
arr

array([[3, 7, 2],
       [5, 2, 1]], dtype=int32)

# Array Inspection

In [20]:
print(arr.shape)       # (2, 3)
print(arr.ndim)        # 2
print(arr.size)        # 6
print(arr.dtype)       # dtype('int64')
print(arr.itemsize)    # bytes per element
print(arr.nbytes)      # total bytes

(2, 3)
2
6
int32
4
24


# Array Slicing

In [22]:
arr

array([[3, 7, 2],
       [5, 2, 1]], dtype=int32)

In [21]:
print(arr[0, 1])        # Element at row 0, col 1
print(arr[1])           # Second row
print(arr[:, 1])        # All rows, second column
print(arr[::2, ::2])    # Stride slicing
print(arr[::-1])        # Reverse array

7
[5 2 1]
[7 2]
[[3 2]]
[[5 2 1]
 [3 7 2]]


# Array reshaping flattening

In [23]:
arr = np.arange(12).reshape(3, 4)   # Shape (3, 4)
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
arr.flatten()                      # 1D version

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
arr.ravel()                        # Similar but returns view

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
arr.T                              # Transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [29]:
arr.reshape(2, 6)                  # Reshape to 2x6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [32]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# Arithmetic Operations

In [33]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x + y # similar to np.add(x, y)

array([5, 7, 9])

In [34]:
x - y # similar to np.subtract(x, y)

array([-3, -3, -3])

In [35]:
x * y # similar to np.multiply(x, y)

array([ 4, 10, 18])

In [37]:
x / y # similar to np.divide(x, y)

array([0.25, 0.4 , 0.5 ])

In [38]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081])

In [39]:
x ** 2 # similar to np.exp(x)

array([1, 4, 9])

# Statistical Operations

In [41]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
np.mean(arr)

np.float64(5.5)

In [43]:
np.median(arr)

np.float64(5.5)

In [45]:
np.std(arr)

np.float64(3.452052529534663)

In [46]:
np.var(arr)

np.float64(11.916666666666666)

In [48]:
np.min(arr)

np.int64(0)

In [49]:
np.max(arr)

np.int64(11)

In [50]:
np.min(arr, axis=0) # check rows

array([0, 1, 2, 3])

In [51]:
np.max(arr, axis=0)

array([ 8,  9, 10, 11])

In [52]:
np.min(arr, axis=1) # check columns

array([0, 4, 8])

# Boolean filtering

In [54]:
arr = np.arange(12).reshape(3, 4)
mask = arr > 3
arr[mask]           # [4 5 6]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

# Changing Data type of array

In [59]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [60]:
arr.astype(str)

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [62]:
arr.astype(bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])